### ISSUE TITLE
Fails with: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by pogilvie** [shunkosa/sfdx-flowdoc-plugin#8]
```
peter: (master):~/Projects/salesforce-> sfdx flowdoc:pdf:generate Asset_Actions -u peter
ERROR running flowdoc:pdf:generate:  Cannot convert undefined or null to object

```
Works when I tried it out from my home machine to a developer org.   Fails on work machine to a sandbox

**Comment by shunkosa** [comment]
@pogilvie Thank you for reporting the issue! Would it be possible if you could upload the process metadata XML file here?

**Comment by pogilvie** [comment]
I'm afraid I can't share the XML as it is company private.  I did retrieve the process builder xml and did not see anything remarkable in it.
Here's some things which might be tricky in it:
RecordType
`<leftValueReference>myVariable_current.RecordType.DeveloperName</leftValueReference>`
condition login
`<conditionLogic>3 AND (1 OR 2)</conditionLogic>`

is there tracing that I can turn on?

**Comment by shunkosa** [comment]
All right! Field referencing is expected to display well. Could you please try to set `development` to `SFDX_ENV` env variable and see what the console says?
<img width="827" alt="スクリーンショット 2020-04-28 7 01 46" src="https://user-images.githubusercontent.com/1404346/80425288-55d0e880-891e-11ea-9881-11c754e5a622.png">

**Comment by pogilvie** [comment]
Well, I reinstalled sfdx-flowdoc-plugin and re-ran it and it worked!  Thank you for looking at this.

**Comment by shunkosa** [comment]
Oh, great to hear that!
